all: build run

clean:
        cd DLL && nmake /f Makefile.win clean
        cd MSX2Core && DEL /S /Q bin obj
        cd Test &&  DEL /S /Q bin obj

build:
        cd DLL && nmake /f Makefile.win all
        cd MSX2Core && dotnet build
        cd Test && dotnet build

run:
        cd Test && dotnet run
