version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install Prerequests"
          command: "sudo apt-get install -y clang dotnet-sdk-6.0"
      - run:
          name: "Build and Test micro MSX2+"
          command: "make"

workflows:
  test-workflow:
    jobs:
      - test
