version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Update apt-get"
          command: "sudo apt-get update"
      - run:
          name: "Install Prerequests"
          command: "sudo apt-get install -y clang wget"
      - run:
          name: "Download .NET Core install script"
          command: "wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh"
      - run:
          name: "chmod .NET Core install script"
          command: "chmod +x ./dotnet-install.sh"
      - run:
          name: "Install .NET Core SDK 7.0"
          command: "./dotnet-install.sh --channel 7.0"
      - run:
          name: "Build and Test micro MSX2+"
          command: "export PATH=/home/circleci/.dotnet:$PATH && make"

workflows:
  test-workflow:
    jobs:
      - test
